### ISSUE TITLE
Game keeps freezing due to recursive call to sendBlockUpdated

### ISSUE THREAD

**Issue by nnmrts** [lebonq/Automatic-Path#47]
Hello! Thanks for the awesome mod!

I just played a session in my singleplayer world and suddenly it kept freezing every few seconds. I thought it might be related to me constantly dying to some modded skeletons, but after I managed to quit the game, I looked at the log and saw this:

```
[19:28:24] [Server thread/ERROR]: recursive call to sendBlockUpdated
java.lang.IllegalStateException: recursive call to sendBlockUpdated
	at net.minecraft.class_3218.method_8413(class_3218.java:985) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:213) ~[client-intermediary.jar:?]
	at fr.lebon.autopath.blocks.PathBlock.method_9591(PathBlock.java:63) ~[autopath-mc1.20.1-1.5.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:755) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2312) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2232) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2719) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:128) ~[client-intermediary.jar:?]
	at fabric.net.mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:682) ~[minecraft-comes-alive-7.5.5+1.20.1-universal.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[client-intermediary.jar:?]
	at net.minecraft.class_1646.method_5773(class_1646.java:320) ~[client-intermediary.jar:?]
	at fabric.net.mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:754) ~[minecraft-comes-alive-7.5.5+1.20.1-universal.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bdg000$carpet$modifiedRunLoop(MinecraftServer.java:15942) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:28:24] [Server thread/ERROR]: recursive call to sendBlockUpdated
java.lang.IllegalStateException: recursive call to sendBlockUpdated
	at net.minecraft.class_3218.method_8413(class_3218.java:985) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:213) ~[client-intermediary.jar:?]
	at fr.lebon.autopath.blocks.PathBlock.method_9591(PathBlock.java:63) ~[autopath-mc1.20.1-1.5.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:755) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2312) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2232) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2719) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.method_6007(class_1429.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bdg000$carpet$modifiedRunLoop(MinecraftServer.java:15942) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:28:24] [Server thread/ERROR]: recursive call to sendBlockUpdated
java.lang.IllegalStateException: recursive call to sendBlockUpdated
	at net.minecraft.class_3218.method_8413(class_3218.java:985) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:213) ~[client-intermediary.jar:?]
	at fr.lebon.autopath.blocks.PathBlock.method_9591(PathBlock.java:63) ~[autopath-mc1.20.1-1.5.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:755) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26318(class_1309.java:2312) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6091(class_1309.java:2232) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2719) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.method_6007(class_1429.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bdg000$carpet$modifiedRunLoop(MinecraftServer.java:15942) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This is just an excerpt and goes on basically forever, until I closed my game. It will probably be fine once I restart the game, but currently I didn't want to play any longer anyway. If it keeps happening, I'll let you know. Btw, this world is several days old by now, and this is the first time this issue came up.

If you need the full log to maybe find out what triggered this issue, please contact me on Discord, my username there is "strmnn".

These are my versions:

Software            | Version
------------------- | -------
Minecraft           | 1.20.1
Fabric Loader       | 0.14.22
Fabric API          | 0.87.0
Automatic Path      | 1.5
a lot of other mods | contact me on Discord for the full modlist

**Comment by lebonq** [comment]
it is a bug, but i have no idea why/how it occurs

**Comment by lebonq** [comment]
Apparently is was a bug from minecraft at the time of 1.20.1 (https://bugs.mojang.com/browse/MC-265239) so i'm closing the issue
